apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: identity
spec:
  selector:
    app: auth-svc
  ports:
    - port: 5008
      targetPort: 5008
      nodePort: 30008          # 固定外部访问端口
  type: NodePort
